### ISSUE TITLE
Speech bubble arrow

### ISSUE THREAD

**Issue by Abbazz2020** [Abbazz2020/article-preview-component-master#1]
I need the Speech bubble arrow to look like the following design

![desktop-active-state-desire](https://user-images.githubusercontent.com/60321696/91337680-9c2d3b80-e788-11ea-81fc-a943742bd489.jpg)

but I can't change from this

![desktop-active-state-reality](https://user-images.githubusercontent.com/60321696/91337748-b6671980-e788-11ea-8b4e-e89995587257.jpg)

This is the CSS code for the speech bubble

```
#speech-bubble {
	width: 250px;
	height: 55px;
	text-align: center;
	background: #49556B;
	filter: drop-shadow(1px 7px 9px #999999);
	position: absolute;
	left: 220px;
	bottom: 130px;
	-moz-border-radius: 10px; 
	-webkit-border-radius: 10px; 
	border-radius: 10px;
}

#speech-bubble:before {
    content: "";
    position: absolute;
    left: 139px;
    width: 0;
    height: 0;
    border-top: 10px solid transparent;
    border-right: 26px solid #49556B;
    border-bottom: 13px solid transparent;
    margin: 45px 0 0 -25px;
}
```

@angelabauer
@oluwaseunasuni
@AnneLivia
@juliatotta
@ValchanOficial
@macedojessica
@iam-abbas
@neodigm
@MatheusWilliam31
@BaseMax
@Obizim
@iamfortune
@timo-cmd
@JoneBulande
@payperlez
@IzabellaRibeiro

**Comment by ValchanOficial** [comment]
I created something like that in Reactjs
https://codesandbox.io/s/speechbubble-3k48b?file=/src/SpeechBubble/styles.js

```css
:after {
    content: "";
    position: absolute;
    display: block;
    width: 0;
    z-index: 1;
    border-style: solid;
    border-color: #3d3d3d transparent;
    border-width: ${({ visible }) => (visible === true ? "10px 10px 0" : 0)};
    bottom: -10px;
    left: 50%;
    margin-left: -10px;
  }
```
you can test on this website:
https://www.html-code-generator.com/css/speech-bubble-generator
